#!/bin/bash
export UNIFYFS_DAEMONIZE=on
export UNIFYFS_MOUNTPOINT=/unifyfs
export UNIFYFS_LOG_DIR=/work/0/NBB/hiraga/work/mpiio-pmembb/src/unifyfs
export UNIFYFS_LOG_VERBOSITY=3
export UNIFYFS_LOGIO_SPILL_DIR=/pmem
export UNIFYFS_LOGIO_SPILL_SIZE=$((2**40+512*2**30))
export UNIFYFS_LOGIO_SHMEM_SIZE=0
export UNIFYFS_LOGIO_CHUNK_SIZE=$((1*2**20))
export UNIFYFS_MARGO_TCP=off
export UNIFYFS_MARGO_CLIENT_TIMEOUT=$((60*1000))
export UNIFYFS_MARGO_SERVER_TIMEOUT=$((60*1000))
export UNIFYFS_RUNSTATE_DIR=/pmem
export UNIFYFS_SERVER_MAX_APP_CLIENTS=4096
export UNIFYFS_SERVER_INIT_TIMEOUT=120
export UNIFYFS_SERVER_LOCAL_EXTENTS=on
export UNIFYFS_CLIENT_LOCAL_EXTENTS=on
export UNIFYFS_CLIENT_NODE_LOCAL_EXTENTS=on
#UNIFYFS_SERVER_CORES 
export UNIFYFS_MARGO_SERVER_POOL_SIZE=8
export UNIFYFS_MARGO_CLIENT_POOL_SIZE=8
